name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: "world"
        type: string

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello ${{ inputs.name }}"
